// Common Companies House PSC nationality values, for the owner-nationality
// filter dropdown. CH stores these as free-text adjectival forms ("British",
// "Nigerian", …); we match case-insensitively against a PSC's `nationality`.
export const COMMON_NATIONALITIES = [
  "British",
  "Irish",
  "Polish",
  "Romanian",
  "Indian",
  "Pakistani",
  "Bangladeshi",
  "Nigerian",
  "Ghanaian",
  "South African",
  "Kenyan",
  "American",
  "Canadian",
  "Australian",
  "Chinese",
  "Hong Kong",
  "Italian",
  "French",
  "German",
  "Spanish",
  "Portuguese",
  "Dutch",
  "Greek",
  "Bulgarian",
  "Lithuanian",
  "Latvian",
  "Hungarian",
  "Turkish",
  "Brazilian",
  "Russian",
  "Ukrainian",
];
